### ISSUE TITLE
Fail to unfurl http://google.com

### ISSUE THREAD

**Issue by maoo** [symphonyoss/bot-unfurl#2]
When trying to unfurl http://google.com url (sending a message `http://google.com` on a 1:1 chat with the bot account), I get the following exception:

```
bot-unfurl_1  | 2016-10-24 12:34:26 ERROR core:0 - Unexpected exception while unfurling url http://google.com
bot-unfurl_1  | java.lang.IndexOutOfBoundsException: No group 2
bot-unfurl_1  |     at java.util.regex.Matcher.start(Matcher.java:375)
bot-unfurl_1  |     at java.util.regex.Matcher.appendReplacement(Matcher.java:880)
bot-unfurl_1  |     at java.util.regex.Matcher.replaceAll(Matcher.java:955)
bot-unfurl_1  |     at clojure.string$replace.invokeStatic(string.clj:106)
bot-unfurl_1  |     at clojure.string$replace.invoke(string.clj:75)
bot-unfurl_1  |     at bot_unfurl.core$process_description.invokeStatic(core.clj:68)
bot-unfurl_1  |     at bot_unfurl.core$process_description.invoke(core.clj:63)
bot-unfurl_1  |     at bot_unfurl.core$unfurl_url_and_build_msg.invokeStatic(core.clj:91)
bot-unfurl_1  |     at bot_unfurl.core$unfurl_url_and_build_msg.invoke(core.clj:81)
bot-unfurl_1  |     at clojure.core$pmap$fn__6970$fn__6971.invoke(core.clj:6736)
bot-unfurl_1  |     at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
bot-unfurl_1  |     at clojure.lang.AFn.call(AFn.java:18)
bot-unfurl_1  |     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
bot-unfurl_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
bot-unfurl_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
bot-unfurl_1  |     at java.lang.Thread.run(Thread.java:745)
```

**Comment by pmonks** [comment]
Bug in [code that hyperlinks hashtags, cashtags, and URLs in unfurled description](https://github.com/pmonks/bot-unfurl/blob/master/src/bot_unfurl/core.clj#L63).  This was previously undetected because Google didn't have any hashtags, cashtags or URLs in their meta information when that code was originally written.
